FROM ubuntu:xenial
MAINTAINER Leonardo Loures <luvres@hotmail.com>

RUN \
	cd \
	&& apt-get update \
	&& apt-get upgrade -y git build-essential cmake libuv1-dev libmicrohttpd-dev \
  \
	&& git clone https://github.com/xmrig/xmrig.git \
	&& cd xmrig \
	&& cmake . \
	&& make -j$(nproc)
