FROM ubuntu:xenial
MAINTAINER Leonardo Loures <luvres@hotmail.com>

ENV WALLET="43oMPyqNyYmP5S4gatvSPKPLD2ysjpdyq63BJx2JWUjHVVCTFTn4ccy9LC1cGGUvApCdCGrECuSf9eo2WHBckfBxNx9Dqkf" \
	POOL="pool.supportxmr.com" \
	PORT="5555" \
	THREADS="8"

RUN \
	cd \
	&& apt-get update \
	&& apt-get upgrade -y git build-essential cmake libuv1-dev libmicrohttpd-dev \
  \
	&& git clone https://github.com/xmrig/xmrig.git \
	&& cd xmrig \
	&& cmake . \
	&& make 
